diffusion:
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

training:
  batch_size: 1
  epochs: 2000
  learning_rate: 1e-4
  device: "cuda"
  data_dir: "./data"
  save_path: "./saves"
  num_workers: 4
  logs: "./logs/train-logs"

inference:
  model_path: "./saves/a.pth"
  device: "cuda"
  logs: "./logs/inference-logs"

api:
  host: "localhost"
  port: 8000
  reload: True

preprocessing:
  data_dir: "./data/plane"
  save_dir: "./data"

model:
  im_channels : 3
  im_size : 32
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  down_sample : [True, True, False]
  time_emb_dim : 512
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 4